import { FiveElement } from './types';

/**
 * The 88 Lumina OH cards.
 * Data derived from the provided CSV datasets.
 */
export const WORDS = [
  { id: 1, text: '揺らぎ (ゆらぎ)', wood: 30, fire: 10, earth: 0, metal: 10, water: 50 },
  { id: 2, text: '静寂 (せいじゃく)', wood: 0, fire: 0, earth: 20, metal: 30, water: 50 },
  { id: 3, text: '焦燥 (しょうそう)', wood: 10, fire: 60, earth: 10, metal: 20, water: 0 },
  { id: 4, text: '祈り (いのり)', wood: 20, fire: 30, earth: 30, metal: 10, water: 10 },
  { id: 5, text: '違和感 (いわかん)', wood: 10, fire: 10, earth: 10, metal: 40, water: 30 },
  { id: 6, text: '孤独 (こどく)', wood: 10, fire: 0, earth: 20, metal: 20, water: 50 },
  { id: 7, text: '安らぎ (やすらぎ)', wood: 20, fire: 10, earth: 50, metal: 10, water: 10 },
  { id: 8, text: '執着 (しゅうちゃく)', wood: 10, fire: 10, earth: 50, metal: 30, water: 0 },
  { id: 9, text: '解放 (かいほう)', wood: 30, fire: 40, earth: 0, metal: 30, water: 0 },
  { id: 10, text: '空虚 (くうきょ)', wood: 0, fire: 0, earth: 30, metal: 20, water: 50 },
  { id: 11, text: 'ときめき (ときめき)', wood: 40, fire: 50, earth: 0, metal: 0, water: 10 },
  { id: 12, text: '罪悪感 (ざいあくかん)', wood: 10, fire: 0, earth: 30, metal: 50, water: 10 },
  { id: 13, text: '受容 (じゅよう)', wood: 30, fire: 10, earth: 40, metal: 0, water: 20 },
  { id: 14, text: '葛藤 (かっとう)', wood: 50, fire: 20, earth: 10, metal: 20, water: 0 },
  { id: 15, text: '渇き (かわき)', wood: 10, fire: 30, earth: 10, metal: 0, water: 50 },
  { id: 16, text: '憧れ (あこがれ)', wood: 40, fire: 30, earth: 10, metal: 20, water: 0 },
  { id: 17, text: '癒し (いやし)', wood: 50, fire: 10, earth: 20, metal: 0, water: 20 },
  { id: 18, text: '戸惑い (とまどい)', wood: 10, fire: 10, earth: 20, metal: 10, water: 50 },
  { id: 19, text: '情熱 (じょうねつ)', wood: 20, fire: 80, earth: 0, metal: 0, water: 0 },
  { id: 20, text: '諦め (あきらめ)', wood: 0, fire: 0, earth: 20, metal: 40, water: 40 },
  { id: 21, text: '勇気 (ゆうき)', wood: 30, fire: 30, earth: 10, metal: 30, water: 0 },
  { id: 22, text: '慈しみ (いつくしみ)', wood: 40, fire: 10, earth: 40, metal: 0, water: 10 },
  { id: 23, text: '本音 (ほんね)', wood: 40, fire: 30, earth: 10, metal: 20, water: 0 },
  { id: 24, text: '建前 (たてまえ)', wood: 10, fire: 10, earth: 30, metal: 50, water: 0 },
  { id: 25, text: '仮面 (かめん)', wood: 10, fire: 10, earth: 20, metal: 50, water: 10 },
  { id: 26, text: '境界線 (きょうかいせん)', wood: 10, fire: 10, earth: 20, metal: 60, water: 0 },
  { id: 27, text: '共鳴 (きょうめい)', wood: 20, fire: 40, earth: 10, metal: 10, water: 20 },
  { id: 28, text: '沈黙 (ちんもく)', wood: 0, fire: 0, earth: 20, metal: 30, water: 50 },
  { id: 29, text: '期待 (きたい)', wood: 30, fire: 30, earth: 20, metal: 10, water: 10 },
  { id: 30, text: '依存 (いぞん)', wood: 10, fire: 0, earth: 40, metal: 0, water: 50 },
  { id: 31, text: '信頼 (しんらい)', wood: 20, fire: 10, earth: 60, metal: 10, water: 0 },
  { id: 32, text: '裏切り (うらぎり)', wood: 0, fire: 20, earth: 10, metal: 50, water: 20 },
  { id: 33, text: '距離感 (きょりかん)', wood: 20, fire: 10, earth: 10, metal: 20, water: 40 },
  { id: 34, text: '絆 (きずな)', wood: 40, fire: 20, earth: 30, metal: 10, water: 0 },
  { id: 35, text: '支配 (しはい)', wood: 10, fire: 20, earth: 20, metal: 50, water: 0 },
  { id: 36, text: '譲歩 (じょうほ)', wood: 20, fire: 10, earth: 50, metal: 20, water: 0 },
  { id: 37, text: '嫉妬 (しっと)', wood: 10, fire: 50, earth: 10, metal: 30, water: 0 },
  { id: 38, text: '許し (ゆるし)', wood: 30, fire: 10, earth: 30, metal: 10, water: 20 },
  { id: 39, text: '孤立 (こりつ)', wood: 10, fire: 0, earth: 20, metal: 40, water: 30 },
  { id: 40, text: '包容 (ほうよう)', wood: 20, fire: 10, earth: 60, metal: 0, water: 10 },
  { id: 41, text: '甘え (あまえ)', wood: 30, fire: 20, earth: 20, metal: 0, water: 30 },
  { id: 42, text: '摩擦 (まさつ)', wood: 20, fire: 40, earth: 10, metal: 30, water: 0 },
  { id: 43, text: '同調 (どうちょう)', wood: 10, fire: 10, earth: 40, metal: 20, water: 20 },
  { id: 44, text: '居場所 (いばしょ)', wood: 30, fire: 10, earth: 50, metal: 0, water: 10 },
  { id: 45, text: '再開 (さいかい)', wood: 50, fire: 30, earth: 10, metal: 10, water: 0 },
  { id: 46, text: '停滞 (ていたい)', wood: 10, fire: 0, earth: 60, metal: 10, water: 20 },
  { id: 47, text: '岐路 (きろ)', wood: 40, fire: 20, earth: 10, metal: 30, water: 0 },
  { id: 48, text: '冒険 (ぼうけん)', wood: 40, fire: 40, earth: 0, metal: 20, water: 0 },
  { id: 49, text: '手放す (てばなす)', wood: 30, fire: 10, earth: 10, metal: 50, water: 0 },
  { id: 50, text: '踏み出す (ふみだす)', wood: 60, fire: 30, earth: 10, metal: 0, water: 0 },
  { id: 51, text: '待機 (たいき)', wood: 10, fire: 10, earth: 40, metal: 10, water: 30 },
  { id: 52, text: '逃避 (とうひ)', wood: 10, fire: 0, earth: 10, metal: 0, water: 80 },
  { id: 53, text: '挑戦 (ちょうせん)', wood: 30, fire: 50, earth: 0, metal: 20, water: 0 },
  { id: 54, text: '準備 (じゅんび)', wood: 20, fire: 10, earth: 40, metal: 30, water: 0 },
  { id: 55, text: '転換 (てんかん)', wood: 40, fire: 30, earth: 10, metal: 20, water: 0 },
  { id: 56, text: '休息 (きゅうそく)', wood: 10, fire: 0, earth: 60, metal: 10, water: 20 },
  { id: 57, text: '模索 (もさく)', wood: 20, fire: 10, earth: 20, metal: 10, water: 40 },
  { id: 58, text: '加速 (かそく)', wood: 20, fire: 60, earth: 0, metal: 20, water: 0 },
  { id: 59, text: '逆行 (ぎゃっこう)', wood: 10, fire: 10, earth: 10, metal: 20, water: 50 },
  { id: 60, text: '開花 (かいか)', wood: 50, fire: 40, earth: 10, metal: 0, water: 0 },
  { id: 61, text: '熟成 (じゅくせい)', wood: 10, fire: 10, earth: 60, metal: 20, water: 0 },
  { id: 62, text: '収穫 (しゅうかく)', wood: 20, fire: 20, earth: 50, metal: 10, water: 0 },
  { id: 63, text: '忘却 (ぼうきゃく)', wood: 0, fire: 0, earth: 20, metal: 30, water: 50 },
  { id: 64, text: '直感 (ちょっかん)', wood: 30, fire: 40, earth: 0, metal: 0, water: 30 },
  { id: 65, text: '習慣 (しゅうかん)', wood: 10, fire: 10, earth: 60, metal: 20, water: 0 },
  { id: 66, text: '終わり (おわり)', wood: 0, fire: 0, earth: 20, metal: 60, water: 20 },
  { id: 67, text: '希望 (きぼう)', wood: 30, fire: 60, earth: 10, metal: 0, water: 0 },
  { id: 68, text: '運命 (うんめい)', wood: 10, fire: 10, earth: 30, metal: 50, water: 0 },
  { id: 69, text: '偶然 (ぐうぜん)', wood: 20, fire: 20, earth: 10, metal: 10, water: 40 },
  { id: 70, text: '秘密 (ひみつ)', wood: 10, fire: 10, earth: 20, metal: 10, water: 50 },
  { id: 71, text: '光 (ひかり)', wood: 20, fire: 80, earth: 0, metal: 0, water: 0 },
  { id: 72, text: '影 (かげ)', wood: 10, fire: 0, earth: 10, metal: 30, water: 50 },
  { id: 73, text: '記憶 (きおく)', wood: 20, fire: 10, earth: 30, metal: 40, water: 0 },
  { id: 74, text: '永遠 (えいえん)', wood: 10, fire: 10, earth: 40, metal: 40, water: 0 },
  { id: 75, text: '刹那 (せつな)', wood: 10, fire: 50, earth: 0, metal: 40, water: 0 },
  { id: 76, text: '真実 (しんじつ)', wood: 10, fire: 10, earth: 20, metal: 60, water: 0 },
  { id: 77, text: '幻 (まぼろし)', wood: 10, fire: 20, earth: 10, metal: 10, water: 50 },
  { id: 78, text: '調和 (ちょうわ)', wood: 20, fire: 20, earth: 20, metal: 20, water: 20 },
  { id: 79, text: '混沌 (こんとん)', wood: 10, fire: 10, earth: 20, metal: 10, water: 50 },
  { id: 80, text: '秩序 (ちつじょ)', wood: 10, fire: 10, earth: 20, metal: 60, water: 0 },
  { id: 81, text: '自由 (じゆう)', wood: 40, fire: 40, earth: 0, metal: 20, water: 0 },
  { id: 82, text: '再生 (さいせい)', wood: 50, fire: 30, earth: 20, metal: 0, water: 0 },
  { id: 83, text: '無常 (むじょう)', wood: 20, fire: 10, earth: 10, metal: 30, water: 30 },
  { id: 84, text: '原点 (げんてん)', wood: 20, fire: 10, earth: 60, metal: 10, water: 0 },
  { id: 85, text: '余韻 (よいん)', wood: 20, fire: 10, earth: 10, metal: 10, water: 50 },
  { id: 86, text: '深淵 (しんえん)', wood: 0, fire: 0, earth: 30, metal: 20, water: 50 },
  { id: 87, text: '導き (みちびき)', wood: 30, fire: 40, earth: 20, metal: 10, water: 0 },
  { id: 88, text: '愛 (あい)', wood: 25, fire: 40, earth: 25, metal: 5, water: 5 },
];

export const IMAGES = [
  { id: 1, description: '雨の窓辺の温かいお茶' },
  { id: 2, description: '深夜の電車' },
  { id: 3, description: '散りゆく桜の花びら' },
  { id: 4, description: '鏡の中の亀裂' },
  { id: 5, description: '都会の自動販売機' },
  { id: 6, description: '舞い散る書類' },
  { id: 7, description: '森の中の孤独なドア' },
  { id: 8, description: '毛糸玉と猫' },
  { id: 9, description: '深海で光る魚' },
  { id: 10, description: '解かれたネクタイとスカーフ' },
  { id: 11, description: '夕暮れのブランコ' },
  { id: 12, description: '枯山水の波紋' },
  { id: 13, description: '手のひらの蛍' },
  { id: 14, description: '都会の空の凧' },
  { id: 15, description: '半開きのブラインド' },
  { id: 16, description: 'スイーツを分かち合う時' },
  { id: 17, description: '玄関に脱ぎ捨てられた靴' },
  { id: 18, description: '洗濯機の泡' },
  { id: 19, description: '鍵穴から漏れる光' },
  { id: 20, description: '色褪せた古い写真' },
  { id: 21, description: '向かい合う二人の定食' },
  { id: 22, description: 'エレベーターの上昇階数' },
  { id: 23, description: '都会のアンテナ' },
  { id: 24, description: '灯されたバースデーキャンドル' },
  { id: 25, description: '滴る雨傘' },
  { id: 26, description: '霜の降りた葉' },
  { id: 27, description: '風に舞うタンポポ' },
  { id: 28, description: '土から顔を出す新芽' },
  { id: 29, description: '巨大な月' },
  { id: 30, description: '清らかな渓流' },
  { id: 31, description: '雷光に照らされた森' },
  { id: 32, description: '雲海に浮かぶ山頂' },
  { id: 33, description: '波打ち際の泡' },
  { id: 34, description: '溶けゆく氷' },
  { id: 35, description: '一面の銀杏の葉' },
  { id: 36, description: '手のひらのマスク' },
  { id: 37, description: 'バッグの中の小物たち' },
  { id: 38, description: '口紅の跡' },
  { id: 39, description: '咲き誇る花束' },
  { id: 40, description: '朝焼けの時計塔' },
  { id: 41, description: '日差しを浴びる向日葵' },
  { id: 42, description: '雪原に残る足跡' },
  { id: 43, description: '光り輝く階段' },
  { id: 44, description: '本に挟んだ押し花' },
  { id: 45, description: '旅支度を整える' },
  { id: 46, description: 'マスク越しの視線' },
  { id: 47, description: 'コンビニ弁当の割引シール' },
  { id: 48, description: '雨傘と桜' },
  { id: 49, description: '新幹線の窓の外の田園' },
  { id: 50, description: '一人カラオケ' },
  { id: 51, description: 'テーブルの上の仮面' },
  { id: 52, description: '並んで海を見る' },
  { id: 53, description: '窓ガラス越しの対話（隔たり）' },
  { id: 54, description: '固く握りしめた手' },
  { id: 55, description: '親友 of 笑い声' },
  { id: 56, description: '人混みの中の逆走者' },
  { id: 57, description: '鏡の中の別人' },
  { id: 58, description: 'イヤホンを分け合う' },
  { id: 59, description: '仲直りのホットココア' },
  { id: 60, description: '蛍の森の出会い' },
  { id: 61, description: 'ひなたぼっこの読書' },
  { id: 62, description: '宙に浮く時計' },
  { id: 63, description: '迷路の出口の光' },
  { id: 64, description: '鳥かごを開ける瞬間' },
  { id: 65, description: '峡谷の虹の橋' },
  { id: 66, description: '金継ぎされた陶器の器' },
  { id: 67, description: '手のひらの光の核' },
  { id: 68, description: '指先を繋ぐ赤い糸' },
  { id: 69, description: '断崖絶壁のブランコ' },
  { id: 70, description: '公園のシャボン玉' },
  { id: 71, description: '祭りの提灯' },
  { id: 72, description: '和傘と現代の傘の交差' },
  { id: 73, description: '枯山水の超現実的な波紋' },
  { id: 74, description: '参拝の柏手' },
  { id: 75, description: 'お守りを受け取る' },
  { id: 76, description: '体と影の分離' },
  { id: 77, description: '北極星を指し示す' },
  { id: 78, description: '森の中の光る扉' },
  { id: 79, description: '風船を積んだ自転車' },
  { id: 80, description: '遠方からの手紙' },
  { id: 81, description: '羽化する蝶' },
  { id: 82, description: 'ビル群の空の凧' },
  { id: 83, description: 'ブラインド越しの光と影' },
  { id: 84, description: '月へ飛ぶ魚' },
  { id: 85, description: '真珠となった涙' },
  { id: 86, description: '水晶の中の満開の庭' },
  { id: 87, description: '夜明けの街並み' },
  { id: 88, description: '回帰原点の円' },
];

/**
 * Construct the 88 Lumina Cards by pairing words and images.
 */
export const LUMINA_CARDS = WORDS.map((word, i) => {
  const image = IMAGES[i];
  const idStr = word.id.toString().padStart(2, '0');
  return {
    id: word.id,
    // Using Firebase Storage bucket for real assets
    imageCardUrl: `https://firebasestorage.googleapis.com/v0/b/lumina-oh-jp.firebasestorage.app/o/oh-cards%2Fimg_${idStr}.jpeg?alt=media`,
    wordCardUrl: `https://firebasestorage.googleapis.com/v0/b/lumina-oh-jp.firebasestorage.app/o/oh-cards%2Fword_${idStr}.jpeg?alt=media`,
    textCardContent: word.text,
    elements: {
      [FiveElement.WOOD]: word.wood,
      [FiveElement.FIRE]: word.fire,
      [FiveElement.EARTH]: word.earth,
      [FiveElement.METAL]: word.metal,
      [FiveElement.WATER]: word.water,
    },
  };
});
